// Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http:www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package sequence

import "strings"

func protocolNameToNumber(name string) string {
	switch strings.ToUpper(name) {
	case "HOPOPT":
		return "0"
	case "ICMP":
		return "1"
	case "IGMP":
		return "2"
	case "GGP":
		return "3"
	case "IPv4":
		return "4"
	case "ST":
		return "5"
	case "TCP":
		return "6"
	case "CBT":
		return "7"
	case "EGP":
		return "8"
	case "IGP":
		return "9"
	case "BBN-RCC-MON":
		return "10"
	case "NVP-II":
		return "11"
	case "PUP":
		return "12"
	case "ARGUS":
		return "13"
	case "EMCON":
		return "14"
	case "XNET":
		return "15"
	case "CHAOS":
		return "16"
	case "UDP":
		return "17"
	case "MUX":
		return "18"
	case "DCN-MEAS":
		return "19"
	case "HMP":
		return "20"
	case "PRM":
		return "21"
	case "XNS-IDP":
		return "22"
	case "TRUNK-1":
		return "23"
	case "TRUNK-2":
		return "24"
	case "LEAF-1":
		return "25"
	case "LEAF-2":
		return "26"
	case "RDP":
		return "27"
	case "IRTP":
		return "28"
	case "ISO-TP4":
		return "29"
	case "NETBLT":
		return "30"
	case "MFE-NSP":
		return "31"
	case "MERIT-INP":
		return "32"
	case "DCCP":
		return "33"
	case "3PC":
		return "34"
	case "IDPR":
		return "35"
	case "XTP":
		return "36"
	case "DDP":
		return "37"
	case "IDPR-CMTP":
		return "38"
	case "TP++":
		return "39"
	case "IL":
		return "40"
	case "IPv6":
		return "41"
	case "SDRP":
		return "42"
	case "IPv6-Route":
		return "43"
	case "IPv6-Frag":
		return "44"
	case "IDRP":
		return "45"
	case "RSVP":
		return "46"
	case "GRE":
		return "47"
	case "DSR":
		return "48"
	case "BNA":
		return "49"
	case "ESP":
		return "50"
	case "AH":
		return "51"
	case "I-NLSP":
		return "52"
	case "SWIPE":
		return "53"
	case "NARP":
		return "54"
	case "MOBILE":
		return "55"
	case "TLSP":
		return "56"
	case "SKIP":
		return "57"
	case "IPv6-ICMP":
		return "58"
	case "IPv6-NoNxt":
		return "59"
	case "IPv6-Opts":
		return "60"
	case "CFTP":
		return "61"
	case "SAT-EXPAK":
		return "63"
	case "KRYPTOLAN":
		return "65"
	case "RVD":
		return "66"
	case "IPPC":
		return "67"
	case "SAT-MON":
		return "68"
	case "VISA":
		return "70"
	case "IPCV":
		return "71"
	case "CPNX":
		return "72"
	case "CPHB":
		return "73"
	case "WSN":
		return "74"
	case "PVP":
		return "75"
	case "BR-SAT-MON":
		return "76"
	case "SUN-ND":
		return "77"
	case "WB-MON":
		return "78"
	case "WB-EXPAK":
		return "79"
	case "ISO-IP":
		return "80"
	case "VMTP":
		return "81"
	case "SECURE-VMTP":
		return "82"
	case "VINES":
		return "83"
	case "TTP":
		return "84"
	case "IPTM":
		return "84"
	case "NSFNET-IGP":
		return "85"
	case "DGP":
		return "86"
	case "TCF":
		return "87"
	case "EIGRP":
		return "88"
	case "OSPFIGP":
		return "89"
	case "Sprite-RPC":
		return "90"
	case "LARP":
		return "91"
	case "MTP":
		return "92"
	case "AX.25":
		return "93"
	case "IPIP":
		return "94"
	case "MICP":
		return "95"
	case "SCC-SP":
		return "96"
	case "ETHERIP":
		return "97"
	case "ENCAP":
		return "98"
	case "GMTP":
		return "100"
	case "IFMP":
		return "101"
	case "PNNI":
		return "102"
	case "PIM":
		return "103"
	case "ARIS":
		return "104"
	case "SCPS":
		return "105"
	case "QNX":
		return "106"
	case "A/N":
		return "107"
	case "IPComp":
		return "108"
	case "SNP":
		return "109"
	case "Compaq-Peer":
		return "110"
	case "IPX-in-IP":
		return "111"
	case "VRRP":
		return "112"
	case "PGM":
		return "113"
	case "L2TP":
		return "115"
	case "DDX":
		return "116"
	case "IATP":
		return "117"
	case "STP":
		return "118"
	case "SRP":
		return "119"
	case "UTI":
		return "120"
	case "SMP":
		return "121"
	case "SM":
		return "122"
	case "PTP":
		return "123"
	case "ISIS":
		return "124"
	case "FIRE":
		return "125"
	case "CRTP":
		return "126"
	case "CRUDP":
		return "127"
	case "SSCOPMCE":
		return "128"
	case "IPLT":
		return "129"
	case "SPS":
		return "130"
	case "PIPE":
		return "131"
	case "SCTP":
		return "132"
	case "FC":
		return "133"
	case "RSVP-E2E-IGNORE":
		return "134"
	case "UDPLite":
		return "136"
	case "MPLS-in-IP":
		return "137"
	case "manet":
		return "138"
	case "HIP":
		return "139"
	case "Shim6":
		return "140"
	case "WESP":
		return "141"
	case "ROHC":
		return "142"
	case "Ethernet":
		return "143"
	}
	return name
}
